version: "3"
services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.10
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  mysql-mospolytech:
    image: "mysql:8.0"
    environment:
      - MYSQL_ROOT_PASSWORD=123qwe
      - MYSQL_DATABASE=session1_xx
    ports:
      - "3306:3306"
    volumes:
      - "mysql-account:/var/lib/mysql"
      - "./server/db/data_dump.sql:/docker-entrypoint-initdb.d/data_dump.sql"
  server-mospolytech:
    build:
      context: ./server
      target: builder
    image: server-mospolytech
    expose:
      - "8086"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server-mospolytech.rule=Host(`127.0.0.1`) && PathPrefix(`/api/server`)"
      - "traefik.http.services.server-mospolytech.loadbalancer.server.port=8086"
    environment:
      - ENV=dev
    volumes:
      - ./server:/go/src/app
volumes:
  mysql-account: